name: Pull Request Build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core CLI
      uses: actions/setup-dotnet@v1.1.0

    - name: Build
      run: dotnet build CommandLineParser.sln -p:Configuration=Release -p:RepositoryUrl=https://github.com/${{ github.repository }}.git -p:RepositoryType=git -o dist

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: dist/*.nupkg