name: Release Tagging

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core CLI
      uses: actions/setup-dotnet@v1.1.0

    - name: Build
      run: |
        VERSION=${{ github.ref_name }}
        dotnet build CommandLineParser.sln -p:Configuration=Release -p:Version=$VERSION -p:RepositoryUrl=https://github.com/${{ github.repository }}.git -p:RepositoryType=git  -o dist
        dotnet nuget push dist\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.nuget_api_key}} 
